apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helloWorld.fullname" . }}
  labels:
    {{- include "helloWorld.labels" . | nindent 4 }}
data:
    {{- toYaml .Values.configMap | nindent 2 -}}