name: CI - render-diff

on:
  pull_request:
    branches:
      - main
    paths:
      - 'tools/render-diff/**'
      - '.github/workflows/ci-render-diff.yml'
      - '!tools/render-diff/README.md'
      - '!tools/render-diff/examples/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tools/render-diff
    steps:
      - name: Checkout
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: '1.24'
          cache-dependency-path: tools/render-diff/go.sum

      - name: Run vet
        run: make vet

      - name: Run lint
        run: make lint

      - name: Run tests
        run: make test
